name: Pull request



on:
  push:
    branches:
    - renovate/**
  pull_request:
    branches:
    - master



jobs:
  build:
    name: Build
    runs-on:
    #- self-hosted
    #- medium
    - ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Run vet
      run: make vet
